### ISSUE TITLE
Dnsmasq 2.84

### ISSUE THREAD

**Issue by Neustradamus** [plamolinux/Plamo-src#1550]
@tenforward: Can you update to 2.84?
- http://lists.thekelleys.org.uk/pipermail/dnsmasq-discuss/2021q1/014640.html

There was a bug in Dnsmasq 2.83.

Changelog:
- http://www.thekelleys.org.uk/dnsmasq/CHANGELOG

**Comment by tenforward** [comment]
@Neustradamus Thanks!! I will update later.

**Comment by Neustradamus** [comment]
@tenforward: Thanks!
